### ISSUE TITLE
Some characters are not properly escaped

### ISSUE THREAD

**Issue by stevemoser** [H2CO3/Plist2ObjC#2]
I have an dictionary that looks like this:
`"ProfileAccountName": "domain\\roger"`
and it is getting converted to this which loses the backslash:
`"ProfileAccountName": "domain\roger"`

**Comment by H2CO3** [comment]
Thanks, fixed in https://github.com/H2CO3/Plist2ObjC/commit/b68b9b79b31f590901506c156238811c1526a220.

**Comment by stevemoser** [comment]
@H2CO3 Thanks! I'll check this out later.
